export default {
  account: true,
  'account-developer': false,
  'account-investor': true,
  profile: true,
  logout: true,
  login: false,
  home: true,
  ranking: true,
  'portfolio-list_released': true,
  'portfolio-detail': true,
  'portfolio-fee': true,
  'portfolio-buy': true,
  'strategy-list_released': true,
  'strategy-detail': true,
  'strategy-fee': true,
  'strategy-buy': true,
  'algorithm-list_released': true,
  'algorithm-detail': true,
  'algorithm-fee': true,
  'algorithm-buy': true,
  'algorithm-release_strategy': true,
  'development-list_to_manage': false,
  'development-edit': false,
  'development-release_algorithm': false,
  'development-release_strategy': false
}
