export default {
  account: false,
  'account-developer': false,
  'account-investor': false,
  profile: false,
  logout: false,
  login: true,
  home: true,
  ranking: true,
  'portfolio-list_released': true,
  'portfolio-detail': true,
  'portfolio-fee': true,
  'portfolio-buy': false,
  'strategy-list_released': true,
  'strategy-detail': true,
  'strategy-fee': true,
  'strategy-buy': false,
  'algorithm-list_released': true,
  'algorithm-detail': true,
  'algorithm-fee': true,
  'algorithm-buy': false,
  'algorithm-release_strategy': false,
  'development-list_to_manage': false,
  'development-edit': false,
  'development-release_algorithm': false,
  'development-release_strategy': false
}
