export default {
  'acount-developer': true,
  'acount-investor': false,
  profile: true,
  logout: true,
  login: false,
  home: true,
  ranking: true,
  'portfolio-list_released': true,
  'portfolio-detail': true,
  'portfolio-fee': true,
  'portfolio-buy': false,
  'strategy-list_released': true,
  'strategy-detail': true,
  'strategy-fee': true,
  'strategy-buy': false,
  'algorithm-list_released': true,
  'algorithm-detail': true,
  'algorithm-fee': true,
  'algorithm-buy': false,
  'algorithm-release_strategy': false,
  'development-list_to_manage': true,
  'development-edit': true,
  'development-release_algorithm': true,
  'development-release_strategy': true
}
